[project]
name = "noark-backbone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "msgpack>=1.1.2",
    "msgpack-numpy>=0.4.8",
    "opencv-contrib-python>=4.13.0.92",
    "pandas>=3.0.2",
    "more-itertools>=10.7.0",
    "polars>=1.40.0",
    "scipy>=1.17.1",
    "toml>=0.10.2",
    "tqdm>=4.67.3",
    "mediapipe>=0.10.35",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "pyrender>=0.1.45",
    "smplx>=0.1.28",
    "trimesh>=4.12.2",
    "maturin>=1.14.1",
    "fiftyone>=1.19.0",
    "requests>=2.34.2",
    "pycocotools>=2.0.11",
    "ultralytics>=8.4.102",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu130"},
]
torchvision = [
  { index = "pytorch-cu130"},
]


[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
